theme: jekyll-theme-giellalt
title: Dictionary for Meadow Mari ⇒ Russian
description: An electronic dictionary from Meadow Mari to Russian

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
